### ISSUE TITLE
reflect-metadata overwrites NodeJs global-variables

### ISSUE THREAD

**Issue by verbraucher** [rbuckton/reflect-metadata#100]
When I have installed and configured "reflect-metadata" in my typescript application with vs2017 and nodejs i get the following error message while I execute the following code.

**My application code**
```TypeScript
...
const port = process.env.port
...
```
**Execution Error**
> .. TS2580	(TS) Cannot find name 'process'...

even the global variable 'global' cannot be found.

**My Configuration**

**tsconfig.json**
```json
...
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "lib": [ "es6" ],
    "sourceMap": true,
    "types": [ "reflect-metadata" ],
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "exclude": [
    "node_modules"
  ]
}
...
```
**package.json**
```json
...
  "devDependencies": {
    "@types/node": "^10.12.15",
    "reflect-metadata": "^0.1.12"
  }
...
```

if I comment out the line  `"types": [ "reflect-metadata" ],` my application will work.
How can I fix this Problem?
Thanks in advance.

**Comment by eppsilon** [comment]
Try adding `"node"` to the `"types"` array. (If "types" is present, only the modules listed are included.)

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

**Comment by rbuckton** [comment]
Correct. Setting `"types"` in your tsconfig.json disables automatic `"types"` detection.

The recommended practices for using `reflect-metadata` with NodeJS is to include the following at the top of your module:

```ts
import "reflect-metadata";
```

This is a feature of ES2015 modules (and is supported down-level in commonjs), that evaluates a module purely for side effects, which would be necessary to use `reflect-metadata`.
