### ISSUE TITLE
Classes are not resolved as valid [[Contructor]] objects

### ISSUE THREAD

**Issue by dkuida** [rbuckton/reflect-metadata#101]
in [here ](https://github.com/rbuckton/reflect-metadata/blob/c2dbe1d02ceb9987f9002eedf0cdb21d74de0019/Reflect.ts#L1494) the actual classes are resolved as non Constructable objects.

I propose to add
`
return typeof argument === "function" || argument.constructor;
`
to resolve that

**Comment by rbuckton** [comment]
Are you talking about class instances (as opposed to the class itself)? Class instances are non-constructable:

```js
class C { }
const obj = new C();
typeof C; // "function"
typeof obj; // "object"
```

**Comment by dkuida** [comment]
you are right - closing. the issue was elsewhere
