### ISSUE TITLE
NPM install failling

### ISSUE THREAD

**Issue by paarceSCT** [rbuckton/reflect-metadata#103]
I'm trying to configure a bitbucket pipeline to deploy my project, I need to install all dependencies in this process so when the system executes npm intall thowrs this error :
`npm ERR! Linux 4.19.23-coreos-r1`
`npm ERR! argv "/bin/versions/node/v4.2.1/bin/node" "/bin/versions/node/v4.2.1/bin/npm" "install"`
`npm ERR! node v4.2.1`
`npm ERR! npm  v2.14.7`
`npm ERR! code EPEERINVALID`
`npm ERR! peerinvalid The package reflect-metadata@0.1.13 does not satisfy its siblings' peerDependencies requirements!`
`npm ERR! Please include the following file with any support request:`
`npm ERR!     /opt/atlassian/pipelines/agent/build/npm-debug.log`

The package.json file has :
"dependencies": {
    ....
    "reflect-metadata": "^0.1.12",
    .....
  }

**Comment by ljharb** [comment]
Run `npm ls` to see how your dependency graph is invalid.

**Comment by paarceSCT** [comment]
The tree is too large so I pasted here just the important lines : 
├--- UNMET DEPENDENCY typeorm@0.2.12
     ├── UNMET PEER DEPENDENCY reflect-metadata@0.1.13 deduped

npm ERR! peer dep missing: jest@>=22 <24, required by ts-jest@23.10.5
npm ERR! peer dep missing: reflect-metadata@0.1.12, required by @nestjs/typeorm@5.2.2
npm ERR! peer dep missing: reflect-metadata@0.1.12, required by @nestjs/typeorm@5.2.2
npm ERR! peer dep missing: reflect-metadata@0.1.12, required by @nestjs/typeorm@5.2.2

**Comment by ljharb** [comment]
Sounds like you need to have an explicit dep on jest 22 or 23, and it sounds like `@nestjs/typeorm@5.2.2` is forcing you to stick to `=0.1.12` - not `^0.1.12`, as it should.

**Comment by paarceSCT** [comment]
@ljharb  You are right it works, thanks.
