### ISSUE TITLE
`[[Metadata]]` property not exists.

### ISSUE THREAD

**Issue by yqz0203** [rbuckton/reflect-metadata#111]
The semantics say that Metadata is stored in Object's `[[Metadata]]` property，but in fact  Metadata is stored in a global WeakMap in the implement codes . Object never has a property named `[[Metadata]]`。

Do I understand something wrong?

**Comment by rbuckton** [comment]
The implementation uses a `WeakMap` to emulate the existence of a possible future `[[Metadata]]` internal slot or similar mechanism.

**Comment by yqz0203** [comment]
@rbuckton I see，thnx.😄😄
