### ISSUE TITLE
Inferred types are set as Object

### ISSUE THREAD

**Issue by canassa** [rbuckton/reflect-metadata#124]
Hello,

Suppose I have the following class

```typescript
class Config {
    @Env TEST = "test string"
}
```

Typescript automatically infers the `TEST` property as `String`, however the `design:type` set on this case is `Object`:

```javascript
class Config {
    constructor() {
        super(...arguments);
        this.TEST = "test string";
    }
}

__decorate([
    config2_1.Env,
    __metadata("design:type", Object)
], Config.prototype, "TEST", void 0);
```

The issue can be workaround by forcing the type:

```
class Config {
    @Env TEST: string = "test string"
}
```

But that can generate some warnings depending on the ts/linter configuration, it's also a bit error-prone.

Is such behavior expected?

**Comment by rbuckton** [comment]
This isn't specifically a `reflect-metadata` issue, but more how TypeScript handles decorator metadata. The emit for this depends on the type annotation. The intent was to avoid type-directed emit and only use what is statically known, though I don't think we fully avoided that (i.e., we resolve the underlying type of a type alias, as long as your type annotation explicitly points to the alias).

**Comment by canassa** [comment]
Hi @rbuckton, thanks for the response!

I am a bit confused, sorry. Does this mean that this is an issue on TypeScript on itself and that I should maybe create a bug for them? Or that this is expected behavior and I should close it?

**Comment by rbuckton** [comment]
You're welcome to file a bug against TypeScript, but as it stands this is the current expected behavior.

**Comment by canassa** [comment]
Thanks!
