### ISSUE TITLE
Tag new version in upstream

### ISSUE THREAD

**Issue by vivekkj123** [rbuckton/reflect-metadata#126]
Hi there,
          Please tag the new version of reflect-metadata (0.1.13) in this github repository... We want to pack your awesome project to Debian. Without tagging new release in this repository, we cant do that...So please solve this ASAP...

Thanks,

VIVEK K J

**Comment by vivekkj123** [comment]
@rbuckton

**Comment by vivekkj123** [comment]
@rbuckton

**Comment by vivekkj123** [comment]
- [ ]  Add tag 0.1.13 in this repo

**Comment by vivekkj123** [comment]
@rbuckton

**Comment by rbuckton** [comment]
I realize it's a bit late, but I've added releases and git tags for 0.1.13 and the more recent releases, and will do a better job about tagging releases in the future.
