### ISSUE TITLE
index.d.ts file, what is the type of function metadata

### ISSUE THREAD

**Issue by workkk98** [rbuckton/reflect-metadata#132]
anyone can explain this question?I dont know this type means.

```ts
    namespace Reflect {
        function metadata(metadataKey: any, metadataValue: any): {
            (target: Function): void;
            (target: Object, propertyKey: string | symbol): void;
        };
    }
```

**Comment by rbuckton** [comment]
It is a function that returns another function with two overloads: one that takes a function and returns `void`, and one that takes an object and property key, and returns `void`.
