### ISSUE TITLE
Throw type error when TS class decorator returns an object.

### ISSUE THREAD

**Issue by ruojianll** [rbuckton/reflect-metadata#139]
```ts
function Deco(){
  return {}
}

@Deco()
class Foo{}
```

TS allows decorator returns any value. When `Reflect.decorate` defined by reflect-metadata, TS will use this function to define metadata instead of TS implements. `Reflect.decorate` couldn't process un-class return value returned by a class decorator.

```js
//Reflect.js
          function DecorateConstructor(decorators, target) {
            for (var i = decorators.length - 1; i >= 0; --i) {
                var decorator = decorators[i];
                var decorated = decorator(target);
                if (!IsUndefined(decorated) && !IsNull(decorated)) {
                    if (!IsConstructor(decorated))
                        throw new TypeError(); // !!HERE!!
                    target = decorated;
                }
            }
            return target;
        }
```

I need the feature that class decorator returns an object.

https://github.com/microsoft/TypeScript/issues/49753

**Comment by DreamMoon93** [comment]
i met the same problem,how to solve?

**Comment by ruojianll** [comment]
@DreamMoon93 According to [tc93 decorator stage 3](https://github.com/tc39/proposal-decorators). Class decorator must return a class constructor. So TS's class decorator is non-standard.

> Class decorators receive the class that is being decorated as the first parameter, and may optionally return a new class to replace it. If a non-constructable value is returned, then an error is thrown.

**Comment by DreamMoon93** [comment]
> so the problem need ts support, or we can do nothing?

**Comment by ruojianll** [comment]
I will try to adapt my code to standard.

**Comment by rbuckton** [comment]
Class decorators should either return a `function` or `void`:

![image](https://user-images.githubusercontent.com/3902892/185687985-18a34964-76fa-442e-995b-229b8eff15fa.png)

TS's `__decorate` helper assumes valid inputs since invalid inputs should result in compile time errors. The `Reflect.decorate` helper does not assume valid inputs and thus is more exhaustive.

**Comment by rdhelms** [comment]
@rbuckton I can't quite tell, but it seems like your response here is assuming stage 2 decorators - is that true? Is there discussion or documentation somewhere on what impact the shift to stage 3 decorators will have on `reflect-metadata`?

**Comment by Limuyang1013** [comment]
I've also met this error and seems only happen on old android machine
