### ISSUE TITLE
build error with typescript 2.0.2 RC

### ISSUE THREAD

**Issue by realityfilter** [rbuckton/reflect-metadata#43]
With the changes described in https://github.com/Microsoft/TypeScript/pull/9646 now there are build errors in projects using reflect-metadata.

We are using angular, webpack and awesome-typescript-loader and experiencing now: 
"File '.../node_modules/reflect-metadata/Reflect.d.ts' not found" error during the build.

Changing import "./reflect-metadata"; to import "./reflect-metadata.d.ts"; in typings.d.ts fixes the problem.

**Comment by rbuckton** [comment]
I believe this was addressed in the release version of TypeScript.
