### ISSUE TITLE
When installed redundantly, Metadata could be erased

### ISSUE THREAD

**Issue by crierr** [rbuckton/reflect-metadata#45]
If multiple node modules have dependencies on 'reflect-metadata' and modules are installed redundantly, metadata is erased after later require('reflect-metadata') is invoked.

Assume that using module Foo and Bar, they're using reflect-metadata
npm package tree looks like below
|─ Foo
|  └ reflect-metadata@0.1.8
|─ Bar
   └ reflect-metadata@0.1.8 

One of my own decorators save something by invoking Reflect.defineMetadata() and another module imports Bar module, so another reflect-metadata module is initialized.
On initialization, reflect-metadata patches its own functions to global Reflect object.
On second initialization, it may overwrite functions, but internal Metadata object will be lost.

I've avoided this problem by specifying same semver version in package.json. latest npm (ver>=3) does not install redundantly.
|─ Foo
|  └ reflect-metadata@0.1.8
|─ Bar

But for the case modules should use different versions or one of them is maintained by others,
it would be great to copy internal Metadata values

**Comment by rbuckton** [comment]
Unfortunately, even if I address this in a later release it is possible an earlier release would still overwrite the members if it is loaded after the earlier release.

**Comment by rbuckton** [comment]
Fixed in 69f4359a4326971fb0318da7dede210d04b2189c
