### ISSUE TITLE
Minified version

### ISSUE THREAD

**Issue by cyrilletuzi** [rbuckton/reflect-metadata#47]
Now that there is a major framework (Angular 2) using reflect-metadata as a production dependency that needs to be loaded by the browser, would it be possible to have a minified JavaScript version included in the package, like other librairies do, to avoid extra build steps ?

**Comment by bomberblue07** [comment]
This issue has been open for months...

**Comment by cyrilletuzi** [comment]
Well, Angular is now using core-js/reflect, so I'm closing the issue.
