### ISSUE TITLE
typings\node.d.ts conflicts with @types/node

### ISSUE THREAD

**Issue by Thieum** [rbuckton/reflect-metadata#60]
When using @types/node over the equivalent typings package, the node.d.ts that ships with the library conflicts with it, as typescript considers that assert is exported twice.

**Comment by rbuckton** [comment]
Which version of reflect-metadata are you using? As of v0.1.9 we no longer use typings and have moved to @types.

**Comment by Thieum** [comment]
@rbuckton 0.1.9 - checked the content of https://registry.npmjs.org/reflect-metadata/-/reflect-metadata-0.1.9.tgz and typings folder is still present, and referenced by test\tsconfig.json. Should I exclude those with gulp?

**Comment by rbuckton** [comment]
You are correct. It looks like v0.1.9 still referenced `typings`. I just published v0.1.10 which contains a bugfix as well as test improvements. I just verified that v0.1.10 does not include `typings` in the package, nor does it include any references.

I would recommend you either update to v0.1.10 or exclude those files from gulp.

**Comment by Thieum** [comment]
Updated to 0.1.10, but still had to exclude the test folder, as tests add a dependency on @types/mocha and chai, which conflicts with jasmine in my setup. Still new to the platform, so not sure if it's an issue or not. I see other libraries using a dist folder to hide the dev dependencies and avoid those conflicts.
