### ISSUE TITLE
Importing reflect-metadata throws an error

### ISSUE THREAD

**Issue by borislemke** [rbuckton/reflect-metadata#68]
I'm filing a
**Support Request**

I'm trying to use Decorators in my node.js app, thus I require to import the library into my app space.
But simply importing / requiring the library throws as error:

In a js file in `www/bin` which starts up the server
```javascript
require('reflect-metadata')
```

or in a TypeScript file in `main.ts`
```typescript
import 'reflect-metadata'
```

Throws

```
/project-path/node_modules/reflect-metadata/Reflect.js:521
                    throw new TypeError();
                    ^

TypeError
    at DecorateConstructor (/project-path/node_modules/reflect-metadata/Reflect.js:521:27)
    at __decorate (/project-path/dist/socket-server/socket_service.js:4:92)
    at Object.<anonymous> (/project-path/dist/socket-server/socket_service.js:32:25)
```

*socket_service.js* line 2 - 7
```javascript
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
```

*socket_service.js* line 32 - 26
```javascript
SocketServiceInjector = __decorate([
    injectable_1.Injectable()
], SocketServiceInjector);
exports.SocketServiceInjector = SocketServiceInjector;
exports.SocketService = SocketServiceInjector;
```

This error occurs after importing `reflect-metadata` although `socket_service` works as intended before importing the library. I haven't used the `Reflect` API yet in any of my code, I was about to but as stated above, simply importing it fails.

**Comment by rbuckton** [comment]
Can you provide the failing source code? [Reflect.js:521](https://github.com/rbuckton/reflect-metadata/blob/master/Reflect.js#L521) throws a `TypeError` if either the return value of the class decorator is something other than `undefined`, `null`, or a `function`.

**Comment by borislemke** [comment]
@rbuckton that explains the error, I was playing around and returned an object(instance of a class) in my class decorator. Fixing this solved my issue. Thank you
