### ISSUE TITLE
Is metadata lost when the file is required?

### ISSUE THREAD

**Issue by nehalist** [rbuckton/reflect-metadata#72]
Is metadata lost when a file is `require`d by node (via `ts-node`)?

For example:

```
// Foo.ts
import 'reflect-metadata';

const AttachMeta = (meta: Object) : ClassDecorator => {
  return (target: any) => {
    Reflect.defineMetadata("custom.metadata", meta, target);
    return target;
  }
}

@AttachMeta({foo: 'bar'})
export class Foo {
  constructor() {}
}

// Logs { foo: 'bar' }
console.log(Reflect.getMetadata("custom.metadata", Foo));
```

Works as intended. Splitting these files and working with `import` also works as intended:

```
import 'reflect-metadata';
import {Foo} from './foo';

// Logs { foo: 'bar' }
console.log(Reflect.getMetadata("custom.metadata", Foo));
```

But when `require`d the metadata is lost:

```
import 'reflect-metadata';

let foo = require('./foo');

console.log(Reflect.getMetadata("custom.metadata", foo));
```

I'm not sure if this is an issue with require, reflect-metadata or something else... the reason why I want to use this is that I've got a directory with many decorated classes which gets metadata from the decorators. A workaround would be to somewhere import these classes at some point - but that would be kinda annoying.

**Comment by Yogu** [comment]
Aren't you missing a `.Foo`? `Foo` is a named export, but you are importing the whole thing.

    let Foo = require('./foo').Foo;
    console.log(Reflect.getMetadata("custom.metadata", Foo));

**Comment by nehalist** [comment]
Oh wow, that's embarrassing... Thanks a lot...
