### ISSUE TITLE
Error when working with another polyfill, like core-js/reflect

### ISSUE THREAD

**Issue by k1r0s** [rbuckton/reflect-metadata#78]
Angular2+ uses core-js/reflect as reflection utility. My library uses reflect-metadata. 

Problem is this library overrides `Reflect` global object causing errors in Angular decorator factory API. 

As you can see in the image below, overriding reflection global object can mess other libraries. Would be better solution check if that object is already defined before reasigning 

![image](https://user-images.githubusercontent.com/6052309/29037126-962a26ee-7ba2-11e7-8f90-04eddecaf16d.png)

**Comment by rbuckton** [comment]
Fixed in 69f4359a4326971fb0318da7dede210d04b2189c
