### ISSUE TITLE
Error TS2394 with Typescript 2.6.1 and "strictFunctionTypes"

### ISSUE THREAD

**Issue by GitStorageOne** [rbuckton/reflect-metadata#83]
Hello!

With Typescript 2.6.1 and "strictFunctionTypes":
node_modules/reflect-metadata/Reflect.ts(194,21): error TS2394: 
Overload signature is not compatible with function implementation.

> 194     export function decorate(decorators: (PropertyDecorator | MethodDecorator)[], target: any, propertyKey: string | symbol, attributes?: PropertyDescriptor | null): PropertyDescriptor | undefined;

**Comment by rbuckton** [comment]
There shouldn't be a need to reference `Reflect.ts` itself as its already compiled. That said, this has already been addressed as of `reflect-metadata@0.2.1`.
