### ISSUE TITLE
Date type is Object

### ISSUE THREAD

**Issue by DevidCIC** [rbuckton/reflect-metadata#84]
Using reflect-metadata with TypeScript. On a parameter of Type Date the type a get through the reflect-metadata library is Object. 

Is there no possibility to get Date back ?

**Comment by 19majkel94** [comment]
@DevidCIC 
I have the same problem, I can't get the `Date` type inside property decorator:
```ts
Reflect.getMetadata("design:type", target, propertyKey);
```
I get only the `Object` function. It works ok with number, strings, custom classes, etc. Also in sources the emitted looks ok and there's `Date`, not `Object`.

However it's weird that when I edit the JS file and add this line in the end, I got proper `Date` function:
```ts
let Rate = class Rate {
};
__decorate([
    Field_1.Field(type => scalars_1.Int),
    __metadata("design:type", Number)
], Rate.prototype, "value", void 0);
__decorate([
    Field_1.Field(),
    __metadata("design:type", Date)
], Rate.prototype, "date", void 0);
__decorate([
    Field_1.Field(),
    __metadata("design:type", User)
], Rate.prototype, "user", void 0);
Rate = __decorate([
    GraphQLType_1.GraphQLType()
], Rate);
exports.Rate = Rate;

console.log("date type", Reflect.getMetadata("design:type", Rate.prototype, "date"));
```

@rbuckton 
Do you have any idea what's going on? Some other stuff has moddified the metadata store?
How can we debug the metadata inside `Reflect`? 😕

**Comment by AlexandreAWE** [comment]
Same problem here, I think is a ts-node issue
