### ISSUE TITLE
Make it an official proposal for ES (?)

### ISSUE THREAD

**Issue by jkrems** [rbuckton/reflect-metadata#9]
This is half question, half suggestion: Are there plans for adding `Reflect.metadata` to the [list of ECMA262 proposals](https://github.com/tc39/ecma262/blob/master/stage0.md)? It seems like there is progress in the TypeScript integration but no trace of adding it to JS proper. I think it would be valuable having it exposed early in that list because it could help direct the conversation about the decorator proposal (e.g. an official way of implementing annotations using decorators instead of just "random code patching/obfuscation").

**Comment by rbuckton** [comment]
Right now we're still working to finalize Decorators for ES2016. Until the Decorators proposal progresses to at least Stage 2, I don't want to complicate the discussion with this proposal. That said, this is very much on the minds of the Decorators champions and the working group responsible for moving Decorators forward.

**Comment by jkrems** [comment]
Thanks for the clarification!

**Comment by MartinJohns** [comment]
> Until the Decorators proposal progresses to at least Stage 2

Decorators are now in Stage 2. https://github.com/tc39/proposals

**Comment by MuYunyun** [comment]
It seems the browser has implemented the Reflect Object.

![image](https://user-images.githubusercontent.com/19354791/47613822-a9b40480-dad0-11e8-80cf-c75ba49614e6.png)

I wonder the ECMA proposals `reflect-metadata` follow isn't  the same as the `Reflect` in the browser(chrome), for example, it has the api Reflect.deleteProperty() in the browser, but I have not found the api in the reflect-metadata.

**Comment by jkrems** [comment]
@MuYunyun The reflect object itself isn't introduced with this proposal. `Reflect.construct` for example was already introduced in ES6/ES2015: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/construct. The metadata proposal just adds additional methods to it.

**Comment by MuYunyun** [comment]
Thanks, I understand, maybe I need some time to research in the difference between them.

**Comment by rektide** [comment]
Would love to see activity from people concerned with this spec in https://github.com/tc39/proposal-decorators/issues/225 or elsewhere on the decorators spec.

**Comment by rbuckton** [comment]
Now that the [Decorator Metadata](https://github.com/tc39/proposal-decorator-metadata) is at Stage 3, it is unlikely that this proposal will be brought to committee.
