### ISSUE TITLE
It it possible to get method visibiility

### ISSUE THREAD

**Issue by tonyxiao** [rbuckton/reflect-metadata#90]
While building a class decorator, it's can be useful to know which methods are private and which ones are not. In particular I'm building a logging decorator and want to log all the public methods.

**Comment by rbuckton** [comment]
While it is possible to record this information, if provided, reflect-metadata does not have any insight or control over what TypeScript emits. You would be able to create a decorator that indicates privacy, but you would likely have to duplicate the privacy on the member, e.g.:

```ts
class C {
  @privacy("private") private m() {}
} 
```

You can always file a suggestion on the https://github.com/Microsoft/TypeScript repo for this as well.

**Comment by tonyxiao** [comment]
Got it, this is useful. Thank you!
